### ISSUE TITLE
FPP setup

### ISSUE THREAD

**Issue by Makeshift-Moose** [ShadowLight8/fpp-to-teensy-serial-ws2813#5]
How do you setup this with universes in FPP?

**Comment by ShadowLight8** [comment]
No problem :) If you have any question, feel free to ask away!

**Comment by processor83** [comment]
Sorry to ask but can you share a screen shot of fpp config .. look to partily work since light flash on the teensy when i test output but no led work.

**Comment by ShadowLight8** [comment]
No problem, let's use the new issue #7 you opened to discuss
