### ISSUE TITLE
FPP config not clear to me

### ISSUE THREAD

**Issue by processor83** [ShadowLight8/fpp-to-teensy-serial-ws2813#7]
Sorry to open issue for this but only way i know how to communicate with you!  Casn you show how to configure this un fpp 4 ? i deos not look to work but when i test display led flash on the teensy..

Thank you

**Comment by processor83** [comment]
so whne i remove <> from header the teensy led flash so it tell me it receive data  when it put <> header then it wont flash but led are not working im on fpp 4.3. serial adapter is TTyAMC0 or 1depending if i reconnect

**Comment by ShadowLight8** [comment]
This is a good way to reach out and I'll try to help!

Here's a screenshot from FPP (I've a few versions old, but nothing has changed):
![FPP-Teensy-config](https://user-images.githubusercontent.com/25712519/98431018-e2075980-207f-11eb-9595-4b39ca62f515.PNG)

You'll need to keep the <> header set. If everything is working correctly, the led on the Teensy shouldn't blink. Make sure that you Channel Count matches the value you're using for the MAX_PIXELS_PER_STRIP (https://github.com/ShadowLight8/fpp-to-teensy-serial-ws2813/blob/master/fpp-to-teensy-serial/fpp-to-teensy-serial.ino#L34).

A trick I found for the port is any time you disconnect the Teensy from the Pi, stop FPP, that will get it to release ttyACM0. When you're ready to reconnect, plug the Teensy in first, then start FPP again. That should keep the Teensy on ttyACM0 each time.

Let me know more about your specific setup and we'll see if we can get stuff working!

**Comment by processor83** [comment]
Ok so here is my setup:
rpi 3 B+
teensy 3.2
octows2811 board
12mm bullet connected to port one data #1 and i tested it with BasicTest.ino and leds all work so i know my wiring is correct,

I tryed to change ws2813 in your sketch by ws2811 in the basic test but it change nothing.

im setup exactly like you in fpp and used your sketch with 517 pixel per port.

**Comment by ShadowLight8** [comment]
Hardware setup all sounds good, especially with BasicTest.ino working correctly. Since you're using MAX_PIXELS_PER_STRIP of 517, then setting the Channel Count to 12408 (517 * 3 * 8) is correct.

In FPP, under Status/Control -> Display Testing, if you turn on Test Mode does anything happen with your LEDs? The led on the Teensy should just stay on.

**Comment by processor83** [comment]
> Hardware setup all sounds good, especially with BasicTest.ino working correctly. Since you're using MAX_PIXELS_PER_STRIP of 517, then setting the Channel Count to 12408 (517 * 3 * 8) is correct.
> 
> In FPP, under Status/Control -> Display Testing, if you turn on Test Mode does anything happen with your LEDs? The led on the Teensy should just stay on.

Nothing on my leds and led on teensy stay on...

**Comment by ShadowLight8** [comment]
Hmm...you might have already tried this, but let's reset and check things just to be sure:
With the Teensy 3.2 connected to the rpi, reboot the rpi, after that check that your GenericSerial config is set to ttyACM0 and Active is still checked. I want to make sure that we're in as much of a known state as possible.

**Comment by processor83** [comment]
here just afther a reboot 
![image](https://user-images.githubusercontent.com/35543827/98431833-ef741200-2086-11eb-8576-014fe98dc3d6.png)

**Comment by ShadowLight8** [comment]
I'm heading out for the evening, but will continue to help tomorrow.

Next step would be to see if we can get the sketch to do something on your leds. In the sketch, in setup(), around leds.begin() (https://github.com/ShadowLight8/fpp-to-teensy-serial-ws2813/blob/master/fpp-to-teensy-serial/fpp-to-teensy-serial.ino#L61) add a setPixel and a 3 second delay. That should light up the first pixel as green. When you run Test Mode, it should go out if the sketch is processing data from the rpi. Let me know how it goes!

```
leds.begin();
leds.setPixel(1, 0, 255, 0);
leds.show();
delay(3000);
```

**Comment by processor83** [comment]
Ok i tested this led 2 is green not led 1... when i send data it will not turn off... if i remove header and test orange on teensy flash but green stay on...

**Comment by processor83** [comment]
Ok i feal so stupif but i found it.. Testing with CPU speed @ 120 Mhz and Optimizations as Fastest with LTO worked well...

is it not just that it work well it wont work if its not set like this!

**Comment by ShadowLight8** [comment]
Don't feel bad! There are a ton of things to check and I'm glad to hear you found the solution! What settings did you have before? I'm surprised it didn't work with other setting, so I might do some testing to see why.

**Comment by processor83** [comment]
it was the default one with a fresh install Faster.
