### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by GAtesz77** [ShadowLight8/fpp-to-teensy-serial-ws2813#9]
Hi!
I want to build this project. How to physically connect Rasbberry and Teensee?
With a cable like that?
https://www.crystalfontz.com/product/wrusby34-micro-usb-to-four-pin-cable
Or do you need a signal level match between the two devices? (5v / 3.3V)

And what controller needs to be set in the FPP to send the data to Teensee? (eg Channel Outputs / Other / GenericSerial Port: ttyama0?)
Thank you.
Regards, Attila

**Comment by ShadowLight8** [comment]
Just a regular USB cable from the Raspberry Pi USB port to the Teensy micro USB port.

Please take a look at the comments in the script, as they covers a lot of setup information.

"Within the sequencing software such as Vixen or Falcon Pi Player (FPP), the serial connection should be configured for MAX_PIXELS_PER_STRIP * 8 * 3 outputs and to send a header of <>" from https://github.com/ShadowLight8/fpp-to-teensy-serial-ws2813/blob/master/fpp-to-teensy-serial/fpp-to-teensy-serial.ino#L36

**Comment by GAtesz77** [comment]
Thank you for answering. In the meantime, I manage to connect them and the system works. But I couldn't go over MAX_PIXELS_PER_STRIP 300. It still works well with 300, it doesn't work above.
What could be the mistake?
I use Teensy 3.2 and Raspberry Pi 2.

**Comment by ShadowLight8** [comment]
There isn't a hard limit, but two things to look at:
When building the scripts, under the Arduino Tools menu, make sure the "USB Type" is set to just "Serial". Testing with CPU speed @ 120 Mhz and Optimizations as Fastest with LTO worked well.

There can also be an issue with where the megaBuffer array gets put in memory. Using an aligned attribute to force the linker to place megaBuffer such that it doesn't cross over the SRAM_L and SRAM_U boundary at 0x20000000. The memory placement can be verified in the fpp-to-teensy-serial.ino.sym file located in C:\Users\<username>\AppData\Local\Temp\arduino_build_<rnd_number> 
Search for megaBuffer - Location should be typically be 20000000 or higher, but at the least, the location + size should not cross 20000000 attribute aligned value must be a power of 2. You might increase aligned(2048) to aligned(4096)
